# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42c377f6673f17cc8a77774a35b468167d8ed4a8ae6e3ca239d3bd57dacd4c3ec836ef6640668bf66f711fb4bb804c1c634c4a8cf1cd68127f87a29e6eaae8be

test:
  secret_key_base: d2f5bc7af7cc9c0bb37775808fcaa2b49de786d758d2a878a25b7a554c413e840755672f89346832d61993662a78c352f2f484717cb808c5afb16f4edc1b6d4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
